const scenes = {
    MAIN: "MAIN",
    SELF: "SELF",
    HYPNO: "HYPNO",
    REGRESSION: "REGRESSION",
    PAYMENT: "PAYMENT",
    MONEY_FREEDOM: "MONEY_FREEDOOM",
    COURSE: "COURSE",
    OPERATOR: "OPERATOR",
    ADMIN_DIALOGE: "ADMIN_DIALOGE",
    PAYMENT_WITH_MONEY_FREEDOM: "PAYMENT_WITH_MONEY_FREEDOM"
}

export default scenes;