const scenes = {
    MAIN: "MAIN",
    HYPNO: "HYPNO",
    RELATIONSHIP: "RELATIONSHIP",
    PAYMENT: "PAYMENT",
    MONEY_FREEDOM: "MONEY_FREEDOOM",
    COURSE: "COURSE",
    OPERATOR: "OPERATOR",
    ADMIN_DIALOGE: "ADMIN_DIALOGE",
}

export default scenes;