const scenes = {
    MAIN: "MAIN",
    HYPNOTHERAPY: "HYPNOTHERAPY",
    HYPNO: "HYPNO",
    RELATIONSHIP: "RELATIONSHIP",
    PAYMENT: "PAYMENT",
    MONEY_FREEDOM: "MONEY_FREEDOOM",
    COURSE: "COURSE",
    OPERATOR: "OPERATOR",
    ADMIN_DIALOGE: "ADMIN_DIALOGE",
    SELF: "SELF",
    REGRESSION: "REGRESSION",
    QUESTION: "QUESTION",
    LOCALE: "LOCALE"
}

export default scenes;